Add minSelect prop (#166)
* Add new prop: `disableRemoveButton`
fix #163

* Add documentation for `disableRemoveButton`
fix #163

* Add example for `disableRemoveButton`
fix #163

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* fix numbering in readme

* Change comment on how to run tests
related #164

* Fix ts linting error on import

* fix tests and pre-commit.ci

Error: Cannot find module '/home/runner/work/svelte-multiselect/svelte-multiselect/src/options' imported from /home/runner/work/svelte-multiselect/svelte-multiselect/tests/multiselect.test.ts

pre-commit.ci:
- hook id: codespell
- exit code: 65

src/options.ts:61: FO ==> OF, FOR, TO, DO, GO
src/options.ts:61: RO ==> TO, ROW, ROB, ROD, ROE, ROT

* Change from disableRemoveBtn to minSelect
As described here:
https://github.com/janosh/svelte-multiselect/issues/163#issuecomment-1319035304

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* move minSelect readme docs to alphabetical order

* tweak minSelect section in Examples.svelte

* add test 'does not render remove buttons if selected.length <= minSelect'

* update repl_url for minSelect example

Co-authored-by: Janosh Riebesell <janosh.riebesell@gmail.com>