drop tests action strategy matrix due to annoying RegExp() inconsistencies on windows
also move vitest tests to tests/unit/*.ts

CI error:
 FAIL  tests/readme.test.ts > readme documents all props and their correct types and defaults
 ❯ tests/readme.test.ts:41:24
AssertionError: expected '<h1 align="center">\r\n  <img src="ht…' to match /1. ```ts\n   activeIndex: .+ = null/
     39|       const expected = new RegExp(`${prop_delim_start}${prop}: .+ = nu…
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

     40|
     41|       expect(readme).to.match(expected)
       |                        ^
     42|     } else {
     43|       expect(readme).to.contain(`${prop_delim_start}${prop}: `)